#
# Docker compose file for TANGO database and database device server
#
# Defines:
#   - tangodb: MariaDB database with TANGO schema
#   - databaseds: TANGO database device server
#
# Requires:
#   - None
#
version: '2'

services:
  tangodb:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-db:${TANGO_DB_TAG}
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=tango
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango

  databaseds:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-cpp:${TANGO_CPP_TAG}
    depends_on:
    - tangodb
    environment:
    - MYSQL_HOST=tangodb:3306
    - MYSQL_DATABASE=tango
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    - TANGO_HOST=databaseds:10000
    entrypoint:
    - /usr/local/bin/wait-for-it.sh
    - tangodb:3306
    - --timeout=30
    - --strict
    - --
    - /usr/local/bin/DataBaseds
    - "2"
    - -ORBendPoint
    - giop:tcp::10000

  tangotest:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-java:${TANGO_JAVA_TAG}
    depends_on:
    - databaseds
    environment:
    - TANGO_HOST=databaseds:10000
    entrypoint:
    - /usr/local/bin/wait-for-it.sh
    - databaseds:10000
    - --timeout=30
    - --strict
    - --
    - /usr/local/bin/TangoTest
    - test
