#!/bin/bash
applet_name=jive3.MainPanel

if [ ! $TANGO_HOST ] && [ -f /etc/tangorc ]; then
   . /etc/tangorc
fi

#
# Define the CLASSPATH
#
JAVALIB=/home/user/tango-9.3.3-rc2/share/java;
JAVABIN=/home/user/tango-9.3.3-rc2/share/java;

ATK=$JAVALIB/ATKCore.jar:$JAVALIB/ATKWidget.jar:$JAVABIN/ATKPanel.jar
LOGVIEWER=$JAVALIB/LogViewer.jar
ASTOR=$JAVALIB/Astor.jar:$JAVALIB/tools_panel.jar
LOG4J=$JAVALIB/log4j.jar
LOGBACK=${TANGO_LOGBACK:-/home/user/tango-9.3.3-rc2/share/tango/logback.xml}

CLASSPATH=$JAVALIB/JTango.jar:$JAVABIN/Jive.jar:$ATK:$LOGVIEWER:$LOG4J:$ASTOR:.
export CLASSPATH

/usr/bin/java \
    -mx128m \
    -DTANGO_HOST=$TANGO_HOST \
    -Dlogback.configurationFile="$LOGBACK" \
    $applet_name $@

