#!/bin/bash

if [ ! $TANGO_HOST ] && [ -f /etc/tangorc ]; then
   . /etc/tangorc
fi

#
# Define the CLASSPATH
#
LOGBACK=${TANGO_LOGBACK:-/usr/local/share/tango/logback.xml}

BASEDIR=/hdbpp_viewer
TANGO=$BASEDIR/JTango.jar
TANGOATK=$BASEDIR/ATKCore.jar:$BASEDIR/ATKWidget.jar
HDBVIEWER=$BASEDIR/jhdbviewer.jar
HDBPP=$BASEDIR/HDBPP.jar
JYTHON=$BASEDIR/jython.jar
JCALENDAR=$BASEDIR/jcalendar.jar
CLASSPATH=$TANGO:$TANGOATK:$HDBVIEWER:$HDBPP:$JYTHON:$JCALENDAR

echo "************************************************"
env
echo "************************************************"

echo "/usr/bin/java -Dlogback.configurationFile="$LOGBACK" -DTANGO_HOST=$TANGO_HOST HDBViewer.MainPanel $@"

/usr/bin/java -Dlogback.configurationFile="$LOGBACK" -DTANGO_HOST=$TANGO_HOST HDBViewer.MainPanel $@
